version: '3.8'

services:
  # Serveur statique
  static-web:
    build: ./static-web-server
    deploy:
      replicas: 3  # Lancer 3 instances
    labels:
      - traefik.http.routers.static-web.rule=Host(`static-web.localhost`)


  # Serveur API
  todolist-api:
    build: ./todolist-api
    deploy:
      replicas: 3  # Lancer 3 instances
    labels:
      - traefik.http.routers.todolist-api.rule=Host(`todolist-api.localhost`)

  # Traefik - Proxy inverse
  reverse_proxy:
    image: traefik
    container_name: reverse_proxy
    command:
      - "--api.insecure=true"           # Active le tableau de bord Traefik
      - "--providers.docker=true"       # Active l'intégration avec Docker
      - "--log.level=DEBUG"         # Logs détaillés (facultatif)
      - "--accesslog=true"          # Activer les logs d'accès

    ports:
      - "80:80"     # Redirection du trafic HTTP
      - "7000:7000" # Pour todolist-api
      - "8080:8080" # Accès au tableau de bord Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik-access.log:/traefik-access.log"  # Fichier de logs

