version: '3.8'

services:
  # Serveur statique
  static-web:
    build: ./static-web-server
    deploy:
      replicas: 3
    labels:
      - traefik.http.routers.static-web.rule=Host(`static-web.localhost`)
      - traefik.http.routers.static-web.entrypoints=https
      - traefik.http.routers.static-web.tls=true       # Active TLS
      - traefik.http.services.static-web.loadbalancer.sticky.cookie=true


  # Serveur API
  todolist-api:
    build: ./todolist-api
    deploy:
      replicas: 3
    labels:
    #sticky session
      - traefik.http.services.todolist-api.loadbalancer.sticky.cookie=true
      - traefik.http.routers.todolist-api.rule=Host(`todolist-api.localhost`)
      - traefik.http.services.todolist-api.loadbalancer.sticky.cookie=true
      - traefik.http.routers.todolist-api.entrypoints=https
      - traefik.http.routers.todolist-api.tls=true
      # Add CORS headers
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://static-web.localhost"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.todolist-api.middlewares=cors@docker"

  # Traefik - Proxy inverse
  reverse_proxy:
    image: traefik
    container_name: reverse_proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "8080:8080"  # Tableau de bord Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik-access.log:/traefik-access.log"
      - "./certificates:/etc/traefik/certificates"  # Monter le dossier contenant les certificats
      - "./traefik.yaml:/etc/traefik/traefik.yaml"   # Monter la configuration Traefik
